-- COMPLETE DATABASE SETUP FOR ISHWAR INTERNATIONAL SCHOOL
-- Run this entire script in Supabase SQL Editor

-- ============================================
-- 1. CREATE TABLES
-- ============================================

-- Hero Slides Table
create table if not exists hero_slides (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  image_url text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Academic Achievers Table
create table if not exists achievers (
  id bigint generated by default as identity primary key,
  name text not null,
  student_class text not null,
  score text,
  category text default 'OTHER',
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Admissions Table
-- Drop existing table to ensure clean schema (WARNING: This deletes all data!)
drop table if exists admissions cascade;

create table admissions (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  dob date,
  gender text,
  class_applying_for text,
  previous_school text,
  last_grade_percentage text,
  father_name text,
  mobile text,
  email text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================
-- 2. CONFIGURE ROW LEVEL SECURITY
-- ============================================
-- This allows public forms to submit without authentication

alter table hero_slides disable row level security;
alter table achievers disable row level security;
alter table admissions disable row level security;

-- ============================================
-- DONE! Your database is now ready.
-- ============================================
