-- Create fees table for admin management
CREATE TABLE IF NOT EXISTS fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL,
  tuition_fee TEXT,
  transport_fee TEXT,
  other_fees TEXT,
  total_fee TEXT,
  display_order INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Disable RLS
ALTER TABLE fees DISABLE ROW LEVEL SECURITY;

-- Insert exact fee data from website (monthly fees, 1st child)
INSERT INTO fees (class_name, tuition_fee, display_order) VALUES
('Nursery', '₹ 2,550', 1),
('L.K.G.', '₹ 3,300', 2),
('U.K.G.', '₹ 3,300', 3),
('1st', '₹ 3,600', 4),
('2nd', '₹ 3,600', 5),
('3rd', '₹ 4,000', 6),
('4th', '₹ 4,000', 7),
('5th', '₹ 4,000', 8),
('6th', '₹ 4,500', 9),
('7th', '₹ 4,500', 10),
('8th', '₹ 4,500', 11),
('9th', '₹ 5,000', 12),
('10th', '₹ 5,000', 13),
('11th/12th (Commerce)', '₹ 5,550', 14),
('11th/12th (Science)', '₹ 5,800', 15);
