-- Create table for Hero Slides
create table if not exists hero_slides (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  image_url text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create table for Academic Achievers
create table if not exists achievers (
  id bigint generated by default as identity primary key,
  name text not null,
  student_class text not null, -- 'X' or 'XII'
  score text,
  category text default 'OTHER', -- 'TOPPER' or 'OTHER'
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create table for Admissions (if not already exists)
create table if not exists admissions (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  dob date,
  gender text,
  class_applying_for text,
  previous_school text,
  last_grade_percentage text,
  father_name text,
  mobile text,
  email text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS) - Optional for now but recommended
-- alter table hero_slides enable row level security;
-- alter table achievers enable row level security;
-- alter table admissions enable row level security;

-- Create policies (Allow public read, authenticated insert/update/delete)
-- You can run these if you want to enforce security, otherwise default is usually public in dev
